name: build-test

on: [push]  
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm run build
      - run: npm run format-check
      - run: npm test
      - run: node index.js
